name: pomodoro
description: pomodoro app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  get_it: ^7.6.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1

flutter:

  uses-material-design: true
